### ISSUE TITLE
Document how to construct `RecordBatch`es

### ISSUE THREAD

**Issue by Ten0** [chmp/serde_arrow#119]
It looks like in the `arrow` crate the idiomatic way to handle arrays coupled with names is to use the [RecordBatch](https://docs.rs/arrow/50.0.0/arrow/array/struct.RecordBatch.html) type, but I [can't find that in the current API](https://docs.rs/serde_arrow/0.9.1/serde_arrow/struct.ArrowBuilder.html#method.build_arrays).

Is this something that is intentional or could that be considered?

**Comment by chmp** [comment]
The initial API of `serde_arrow` was based around record batches. However, the arrow crate is released at a high frequency (every 6 weeks) and breaks its API quite their frequently. Therefore I made the concious decision to minimize the API used by `arrow` (hence also the whole machinery to construct the underlying buffers). 

Another reason is symmetry to the `arrow2` crate which does not have a `RecordBatch` abstraction. However, as this crate seems to be in the process of being deprecated, this reason is less a pressing one.

My personal opionion is that its acceptable to require the users of `serde_arrow` to execute the extra steps of constructing the record batch:

```rust
let arrays = serde_arrow::to_arrow(&fields, &items)?;
let schema = Schema::new(fields);
let record_batch = RecordBatch::try_new(Arc::new(schema), Arc::new(fields))?;
```

It should be implemented though :)

**Comment by chmp** [comment]
Will be documented with #126
